config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  
  get '/search' => 'searches#search'
  
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  # 自分がフォローされる側（被フォロー）の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする側（与フォロー）の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

  # 自分をフォローしている人を参照。被フォロー関係を通じて、自分をフォローしている人（follower）を参照。
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 自分がフォローしている人を参照。与フォロー関係を通じて、自分にフォローされている人（followed）を参照。
  # 自分がフォローしている人＝自分にフォローされている人（followed）
  has_many :followings, through: :relationships, source: :followed
  
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  # カラムはprofile_image_id、ここでは_idはいらない。（rails7章）
  attachment :profile_image, destroy: false
  
  # nameが空or２文字以下だとエラー
  # アプリ側とDB側の両方に記述する必要があった。
  validates :name, presence: true, length: {minimum: 2, maximum: 20}, uniqueness: true
  
  # introduction 最大５０文字
  validates :introduction, length: {maximum: 50}
  
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]
  
  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end
  
  def show
    @user = User.find(params[:id])
    # userのbooks
    @books = @user.books 
    @book = Book.new
    # @books = Book.where(user_id: @user.id)
  end
  
  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end
  
  # def following #フォロワー一覧
    # @user = User.find(params[:id])
  # end

  # def followed #フォロー一覧
    # @user = User.find(params[:id])
  # end
  
  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)  
  end
  
  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpeg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_userinfo.html.erb
<table class="table">
    <tr>
      <%= attachment_image_tag user, :profile_image, :full, 100, 100, fallback: "no_image.jpeg" %>
    </tr>
    <tr>
      <th>Name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>Introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>follows</th>
      <th><%= link_to user.followings.count, user_followings_path(user) %></th>
    </tr>
    <tr>
      <th>followers</th>
      <th><%= link_to user.followers.count, user_followers_path(user) %></th>
    </tr>
  </table>
  
  <div class="row">
    <% if current_user != user %>
      <% if current_user.following?(user) %>
        <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
      <% end %>
    <% else %>
      <%= link_to edit_user_path(user), class:"btn btn-default btn-block" do %>
        <span class="fas fa-user-cog"></span>
      <% end %>
    <% end %>
  </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      
    <h2>User info</h2>

    <%= form_with model:@user, local:true do |f| %>
    
      <%= render 'books/error', model: @user %>
      
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>

    <% end %>
  
 </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/userinfo', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render 'users/index', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/userinfo', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 -offset-md-1">
      <h2>Books</h2>
      <%= render 'books/index', books: @books %>
    </div>
  </div>
</div>