config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  
  get '/search' => 'searches#search'
  
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  
  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  
  
  # 上からプログラムが実行されるため、
  # @bookの変数がBook.newになり、何もない状態になっているため、
  # showアクションを起こしても変数が'nil'になってしまう！（メンターさん）
  # 変数名をどちらか変更すれば良い
  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end
  
  def index
    @user = User.find(current_user.id)
    @book = Book.new
    @books = Book.all
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @user = User.find(current_user.id)
      @books = Book.all
      render "index"
    end
  end
  
  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      redirect_to books_path, notice: "Book was successfully destroyed."
    end
  end
  
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_error.html.erb
<% if model.errors.any? %>
  <div class="error">
    <h3><%= model.errors.count %> errors prohibited this obj from being saved</h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/_form.html.erb
<%= form_with model:book, local:true do |f| %>
      <!--title-->
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
      <!--opinion-->
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
      <!--Create Book  New bookを作成-->
  <div class="form-group">
    <%= f.submit  class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr id="book_<%= book.id %>">
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpeg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <!--<td>%= link_to book.title, book_path(book) %></td>-->
        <td><%= book.body %></td>
        <td class="favorite-btn"><%= render "favorites/favorite-btn", book: book %></td>
        <td>コメント数：<%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= render 'books/error', model: @book %>
      <%= render 'books/form', book: @book %>
      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>
    </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'books/error', model: @book %>
  <!--左側-->
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/userinfo', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <!--右側-->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render 'books/index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<!--投稿詳細-->
<div class="container">
  <!--サイドバー-->
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/userinfo', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book_new %>
      <!--%= render 'books/form', book: @book_new %>-->
    </div>
    <!--投稿詳細-->
    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
      <table class="table">
        <tr id="book_<%= @book.id %>">
          
          <td>
            <%= link_to user_path(@book.user) do %>
              <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpeg" %><br>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <!--いいね機能-->
          <td class="favorite-btn"><%= render "favorites/favorite-btn", book: @book %></td>
          <!--コメント数-->
          <td>コメント数：<%= @book.book_comments.count %></td>
          <!--Edit,Destroy-->
          <% if user_signed_in? && current_user.id == @book.user_id %>
            <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success btn-sm" %></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class: "btn btn-danger btn-sm" %></td>
          <% end %>
          <!--コメントフォーム-->
          <%= render 'book_comments/comment', book: @book, book_comment: @book_comment %>
          
          <!--edit,destroy-->
          <!--% if @book.user_id == current_user.id %>-->
            <!--<td>%= link_to "Edit", edit_book_path(@book), class:"btn btn-success"%></td>-->
            <!--<td>%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger" %></td>-->
          <!--% end %>-->
          
        </tr>
      </table>
    </div>
  </div>
</div>