config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  
  get '/search' => 'searches#search'
  
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
end

app/views/layouts/_search.html.erb
<div class="search-form">
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content %>
    <%= f.select :model, options_for_select({ "User" => "user", "Book" => "book" }) %>
    <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
    <%= f.submit '検索' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!--<script src="https://kit.fontawesome.com/0cc79d929d.js" crossorigin="anonymous"></script>-->
    <!--<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">-->
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <nav class="navbar-brand">
            <%= link_to "Bookers", root_path %>
          </nav>
        </nav>
        
        <nav>
          <ul class="nav justify-content-end ml-auto">
            <% if user_signed_in? %>
        <!--ログイン時、Home.Users.Books.logoutをヘッダーに表示-->
              <li class="nav-item nav-link">
                <%= link_to "Home", user_path(current_user.id), class: "fas fa-home" %>
              </li>
              <li class="nav-item nav-link">
                <%= link_to "Users", users_path, class: "fas fa-users" %>
              </li>
              <li class="nav-item nav-link">
                <%= link_to "Books", books_path, class: "fas fa-book-open" %>
              </li>
              <li class="nav-item nav-link">
                <%= link_to "logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt" %>
              </li>
            <% else %>
        <!--ログインしてない場合は、Home,About,sign up loginをヘッダーに表示-->
              <li class="nav-item nav-link">
                <%= link_to "Home", root_path, class: "fas fa-home" %>
              </li>
              <li class="nav-item nav-link">
                <%= link_to "About", home_about_path, class: "fas fa-link" %>
              </li>
              <li class="nav-item nav-link">
                <%= link_to "sign up", new_user_registration_path, class: "fas fa-user-plus" %>
              </li>
              <li class="nav-item nav-link">
                <%= link_to "login", new_user_session_path, class: "fas fa-sign-in-alt" %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    
    <% if user_signed_in? %>
      <%= render 'layouts/search' %>
    <% end %>
    
    <%= yield %>
    
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto aline center">CopyRight Infratop.inc</div>
        </div>
      </div>
    </footer>
  </body>
</html>